### ISSUE TITLE
Unlink command does not remove the `.powder` file

### ISSUE THREAD

**Issue by besi** [powder-rb/powder#126]
### What I did

``` shell
powder unlink
```

> Successfully removed foo-bar

``` shell
powder link foo
```

> Successfully removed foo-bar
> Cowardly refusing to overwrite .powder
### Expected Result

At this point I would expect that I can create a new link for the application.

Thanks for considering this

**Comment by philnash** [comment]
When you `unlink` you can pass the option `--delete` which will remove the `.powder` file.

When you `link` you can pass the option `--force` which will overwrite the `.powder` file.
