### ISSUE TITLE
What is powders take one the HSTS issue?

### ISSUE THREAD

**Issue by NielsKSchjoedt** [powder-rb/powder#134]
The pow repository was recently updated on the matter

https://github.com/basecamp/pow/pull/547

How can we get powder to work again?

**Comment by hamitturkukaya** [comment]
Pull request waiting but you can also change POW_DOMAINS variable from ~/.powconfig file. (If you don't have just create it)

```bash
export POW_DOMAINS=test
```

**Comment by philnash** [comment]
I think it's absolutely correct to follow the pow project with this, thanks for bringing this up @NielsKSchjoedt and thanks for the PR @hamitturkukaya, it's merged and released as version 0.4.0.
